# Generated by Django 2.2.6 on 2022-12-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221215_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='price',
        ),
    ]
